### ISSUE TITLE
Fix code scanning alert - DOM text reinterpreted as HTML

### ISSUE THREAD

**Issue by blokhin** [basf/bscience-gui#20]
Tracking issue for:
- [ ] https://github.com/basf/bscience-gui/security/code-scanning/2

@Valexr should we simply ignore it?

**Comment by Valexr** [comment]
> Tracking issue for:
> 
> * [ ]  https://github.com/basf/bscience-gui/security/code-scanning/2
> 
> @Valexr should we simply ignore it?

I don’t see where it…🤷🏻‍♂️but for more security we can sanitize string before pass to server…🤔on client side it’s hasn’t any risks…

**Comment by Valexr** [comment]
Fixed https://github.com/basf/bscience-gui/pull/19/commits/6ebbcfd143621ae5e1ef91ac0e0c9c66c77b909e
